import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export interface DetectionResult {
  overallProbability: number; // 0 to 100
  confidenceScore: number; // 0 to 100
  analysisSummary: string;
  flaggedPassages: {
    text: string;
    reason: string;
    probability: number;
  }[];
  linguisticMarkers: {
    marker: string;
    finding: string;
    impact: "high" | "medium" | "low";
  }[];
  verdict: "Likely Human" | "Uncertain" | "Likely AI" | "Highly Likely AI";
}

export async function analyzeSubmission(text: string): Promise<DetectionResult> {
  const response = await ai.models.generateContent({
    model: "gemini-3.1-pro-preview",
    contents: `Analyze the following legal submission for signs of AI generation (LLM usage). 
    As a forensic linguist specializing in legal academia, evaluate the text for:
    1. Perplexity and Burstiness patterns typical of LLMs.
    2. Over-reliance on generic legal templates vs. specific case analysis.
    3. Linguistic "fingerprints" of models like GPT-4, Claude, or Gemini (e.g., specific transition phrases, hedging, or overly balanced structures).
    4. Consistency of voice and depth of legal reasoning.

    Submission Text:
    """
    ${text}
    """`,
    config: {
      systemInstruction: "You are an expert forensic linguist and law school dean. Your goal is to provide a highly accurate, evidence-based assessment of whether a text was generated by an AI. Be objective, precise, and provide specific evidence for your findings. Return the result in a structured JSON format.",
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          overallProbability: { type: Type.NUMBER, description: "Percentage probability that the text is AI-generated (0-100)" },
          confidenceScore: { type: Type.NUMBER, description: "Confidence in this assessment (0-100)" },
          analysisSummary: { type: Type.STRING, description: "A detailed summary of the forensic findings" },
          verdict: { type: Type.STRING, description: "The final verdict: Likely Human, Uncertain, Likely AI, or Highly Likely AI" },
          flaggedPassages: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                text: { type: Type.STRING, description: "The specific text snippet flagged" },
                reason: { type: Type.STRING, description: "Why this snippet is suspicious" },
                probability: { type: Type.NUMBER, description: "Probability this specific snippet is AI (0-100)" }
              },
              required: ["text", "reason", "probability"]
            }
          },
          linguisticMarkers: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                marker: { type: Type.STRING, description: "The name of the linguistic marker (e.g., 'Syntactic Uniformity')" },
                finding: { type: Type.STRING, description: "What was observed" },
                impact: { type: Type.STRING, enum: ["high", "medium", "low"], description: "Impact on the final score" }
              },
              required: ["marker", "finding", "impact"]
            }
          }
        },
        required: ["overallProbability", "confidenceScore", "analysisSummary", "verdict", "flaggedPassages", "linguisticMarkers"]
      }
    }
  });

  try {
    const result = JSON.parse(response.text || "{}");
    return result as DetectionResult;
  } catch (error) {
    console.error("Failed to parse Gemini response:", error);
    throw new Error("Analysis failed. Please try again.");
  }
}
